/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StatistcsJFrame.java
 *
 * Created on 2012-7-24, 20:45:28
 */
package com.carpark.view;

import com.Idao.ICustomerDao;
import com.Idao.IRecordDao;
import com.Idao.ISpaceDao;
import com.dao.CustomerDao;
import com.dao.RecordDao;
import com.dao.SpaceDao;
import com.vo.Customer;
import com.vo.Record;
import com.vo.Space;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.List;

/**
 *
 * @author Zeming
 */
public final class StatisticsJFrame extends javax.swing.JFrame {

    private ISpaceDao spaceDao;//对场地操作的全局变量
    private Space space;
    private IRecordDao recordDao;//对记录操作的全局变量
    private Record record;
    private ICustomerDao customerDao;
    private Customer customer;

    /** Creates new form StatistcsJFrame */
    public StatisticsJFrame() {
        initComponents();
        initData();
    }

    public void initData() {
        spaceDao = new SpaceDao();
        List spaceList = spaceDao.findAllSpace();
        //初始化场地使用各个状态的数量为0
        int free = 0, busy = 0, maintain = 0;
        //如果符合要求，状态数量加一
        for (int i = 0; i < spaceList.size(); i++) {
            space = (Space) spaceList.get(i);
            if (space.getState() == 0) {
                free++;
            } else if (space.getState() == 1) {
                busy++;
            } else if (space.getState() == 2) {
                maintain++;
            }
        }
        //显示场地在用状况
        jLabel4.setText("可用" + free + "个，在用" + busy + "个，维护" + maintain + "个");



        //统计营收情况
        recordDao = new RecordDao();
        List recordList = recordDao.findAllRecord();
        //获取现在的时间 
        Timestamp d = new Timestamp(System.currentTimeMillis());
        //定义时间格式
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        //格式化当前时间 
        String nowDate = sdf.format(d);
        //初始化收入金额
        int income = 0;
        //统计结束时间是今天的营收情况
        for (int i = 0; i < recordList.size(); i++) {
            record = (Record) recordList.get(i);
            //先判断是否为空值
            if (record.getEtime() != null) {
                if (sdf.format(record.getEtime()).equals(nowDate)) {
                    income += record.getPay();
                }
            }
        }
        jLabel5.setText("今日收入" + income + "元");

        //统计开卡情况
        customerDao = new CustomerDao();
        List customerList = customerDao.findAllCustomer();
        //初始化开卡的数量
        int temp = 0, vip = 0, add = 0;
        for (int i = 0; i < customerList.size(); i++) {
            customer = (Customer) customerList.get(i);
            //统计今日开卡情况
            if (sdf.format(customer.getRegisterDate()).equals(nowDate)) {
                add++;
            }
            //统计会员卡和临时卡的数量
            if (customer.getCtype() == 0) {
                temp++;
            } else if (customer.getCtype() == 1) {
                vip++;
            }
        }
        //显示到窗体
        jLabel7.setText("现有会员卡" + vip + "张，临时卡" + temp + "张，今日开卡" + add + "张");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.carpark.view.CarParkApp.class).getContext().getResourceMap(StatisticsJFrame.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setFont(resourceMap.getFont("jLabel7.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StatisticsJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
